spring:
  thymeleaf:
    cache: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/app}
    username: ${SPRING_DATASOURCE_USERNAME:app}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:__unset__}}
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          azure:
            client-id: ${AZURE_CLIENT_ID:__unset__}
            client-secret: ${AZURE_CLIENT_SECRET:__unset__}
            scope: openid, profile, email, User.Read
            provider: azure
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          github:
            client-id: ${GITHUB_CLIENT_ID:__unset__}
            client-secret: ${GITHUB_CLIENT_SECRET:__unset__}
            scope: read:user, user:email
            provider: github
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/${AZURE_TENANT_ID:common}/v2.0
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

server:
  servlet:
    session:
      cookie:
        same-site: lax

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    env:
      keys-to-sanitize: password,secret,token,key,client-secret,github_client_secret,azure_client_secret,spring.datasource.password
