spring:
  datasource:
    url: jdbc:h2:mem:hello;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
