server:
  port: 3000

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:mem:hello;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  # In later phases we will configure the GitHub redirect URI override and dev datasource here.
